version: "3"
services:
  minio:
    container_name: Minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - '9010:9000'
      - '9001:9001'
    volumes:
      - /tmp/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_secret
    secrets:
      - minio_secret
    restart: unless-stopped
    
secrets:
  minio_secret:
    file: ./minio_pw.txt